### PR TITLE
Df branch - Add/Remove a Tag to/from a Post

### PR DESCRIPTION
**Pull request by DeVanteFarmer**
#17 Add a Tag to a Post - https://trello.com/c/e4uRl2sb
#18 Remove a Tag from a Post - https://trello.com/c/irO6nOiz

**Description**
This PR implements an author feature that allows users to add, edit, and delete tags in the PostDetails section of the TabloidFullStack application. _For the time being, all users are treated as admins, with future stories planned to enforce user permissions._

**Type of Change**
Enhancement (non-breaking change that improves existing functionality)

**Changes Made**

PostDetails Page:
Created add/remove functions for Tags per Post

Controller Methods:
Added AddTagsToPost, and RemoveTagFromPost methods in the PostController.

Frontend Changes:
Created new functions for Tags in the PostDetails page.

**Testing Instructions**

1. Preparation:
- Ensure all your local changes are committed and pushed to your branch.
- Switch to the main branch and update it with the latest changes:
- Ensure the latest version of the main branch is pulled (git pull origin main).
- git fetch --a will give you access to my branch "df-branch"
- git checkout df-branch to switch to my branch
- If you don't see the most recent version of my files, try git pull origin df-branch
- If you haven't already created the Tabloid database, please do so using the provided SQL scripts.
- Use this https://github.com/NewForce-Cohort-9/tabloid-full-stack-code-crusaders/blob/main/SQL/01_Tabloid_Create_DB.sql to define the necessary tables and columns.
- Use this https://github.com/NewForce-Cohort-9/tabloid-full-stack-code-crusaders/blob/main/SQL/02_Tabloid_Seed_Data.sql to populate the database with initial data.
- Launch the Application:
- After ensuring your environment is properly set up, launch the application by clicking the "Start with Debugger" (green play button) in your IDE.
- Log In:
- Open the application in your browser.
- Navigate to the Login page via the navbar and log in with the following credentials:
- Email: "foo@bar.com"
- Password: Use any password of your choosing.
- After logging in, you will be redirected to the homepage.

2. Navigate to Post Details:
- From the homepage, click on the Posts link in the navbar.
- Click on the post of the logged in user. (First post listed)

3. Verify:
- Add a Tag to the post . 
- Remove the Tag you just added from the post . 

**Checklist:**
- [x]  My code follows the style guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly in hard-to-understand areas.
- [x]  My changes generate no new warnings or errors.
- [x]  I have added test instructions that prove my feature works.

### CODE REVIEW

**Comment by cbrooks62** [comment]
looks good

**Comment by Revvvolution** [comment]
It is working, but I'm getting a break message when there's more than one tag selected. Is there a way to throw an alert when someone is trying to save this way?

**Comment by DeVanteFarmer** [comment]
Yes i will fix this @Revvvolution

**Comment by Revvvolution** [comment]
This works incredibly well!

**Pull request merged**
